version: "3"
services:
    mongodb:
        image: mongo
        ports:
            - "27017:27017"
    projects-manager-server:
        build: .
        depends_on:
            - mongodb
        ports:
            - "3000:3000"
        volumes:
            - ./src/:/usr/app/src/
            - ./.env:/usr/app/.env
            - ./package.json:/usr/app/package.json
            - ./yarn.lock:/usr/app/yarn.lock
            - ./tsconfig.json:/usr/app/tsconfig.json
            - ./tsconfig.build.json:/usr/app/tsconfig.build.json
            - ./node_modules:/usr/app/node_modules
        command: yarn start:dev